import { PropertyTemplate } from '../types/template';

export const PROPERTY_TEMPLATES: PropertyTemplate[] = [
    {
        id: 'apartment',
        name: 'templates.apartment.name',
        description: 'templates.apartment.description',
        icon: '🏢',
        inputs: {
            kupnaCena: 150000,
            vlastneZdroje: 30000,
            vyskaHypoteky: 120000,
            urok: 4.5,
            dobaSplatnosti: 25,
            ocakavaneNajomne: 700,
            obsadenost: 95,
            fondOprav: 50,
            sprava: 70,
            poistenie: 25,
            danZNehnutelnosti: 300,
            energie: 80,
            internet: 20,
            ineNaklady: 30,
            neocakavaneNaklady: 50,
        },
    },
    {
        id: 'house',
        name: 'templates.house.name',
        description: 'templates.house.description',
        icon: '🏠',
        inputs: {
            kupnaCena: 250000,
            vlastneZdroje: 50000,
            vyskaHypoteky: 200000,
            urok: 4.5,
            dobaSplatnosti: 25,
            ocakavaneNajomne: 1200,
            obsadenost: 90,
            fondOprav: 100,
            sprava: 120,
            poistenie: 40,
            danZNehnutelnosti: 500,
            energie: 150,
            internet: 25,
            ineNaklady: 50,
            neocakavaneNaklady: 80,
        },
    },
    {
        id: 'commercial',
        name: 'templates.commercial.name',
        description: 'templates.commercial.description',
        icon: '🏪',
        inputs: {
            kupnaCena: 400000,
            vlastneZdroje: 100000,
            vyskaHypoteky: 300000,
            urok: 5.0,
            dobaSplatnosti: 20,
            ocakavaneNajomne: 2500,
            obsadenost: 85,
            fondOprav: 200,
            sprava: 250,
            poistenie: 80,
            danZNehnutelnosti: 1200,
            energie: 300,
            internet: 30,
            ineNaklady: 100,
            neocakavaneNaklady: 150,
        },
    },
];
